import {
  BadgePercent,
  Bell,
  Boxes,
  Building2,
  ClipboardList,
  CreditCard,
  FileBarChart,
  LayoutDashboard,
  Package,
  PackagePlus,
  Percent,
  Settings,
  ShoppingCart,
  Star,
  Tags,
  Users,
  Wallet,
} from "lucide-react";

export const vendorNav = [
  { label: "Dashboard", to: "/vendor/dashboard", icon: LayoutDashboard },
  { label: "Products", to: "/vendor/products", icon: Package },
  { label: "Add Product", to: "/vendor/products/add", icon: PackagePlus },
  { label: "Orders", to: "/vendor/orders", icon: ShoppingCart },
  { label: "Inventory", to: "/vendor/inventory", icon: Boxes },
  { label: "Earnings", to: "/vendor/earnings", icon: Wallet },
  { label: "Payouts", to: "/vendor/payouts", icon: CreditCard },
  { label: "Reviews", to: "/vendor/reviews", icon: Star },
  { label: "Profile", to: "/vendor/profile", icon: Building2 },
  { label: "Settings", to: "/vendor/settings", icon: Settings },
];

export const adminNav = [
  { label: "Dashboard", to: "/admin/dashboard", icon: LayoutDashboard },
  { label: "Vendors", to: "/admin/vendors", icon: Building2 },
  { label: "Customers", to: "/admin/customers", icon: Users },
  { label: "Products", to: "/admin/products", icon: Package },
  { label: "Categories", to: "/admin/categories", icon: Tags },
  { label: "Inventory", to: "/admin/inventory", icon: Boxes },
  { label: "Orders", to: "/admin/orders", icon: ClipboardList },
  { label: "Payments & Matching", to: "/admin/payments", icon: CreditCard },
  { label: "Commissions", to: "/admin/commissions", icon: Percent },
  { label: "Payouts", to: "/admin/payouts", icon: Wallet },
  { label: "Coupons", to: "/admin/coupons", icon: BadgePercent },
  { label: "Reports", to: "/admin/reports", icon: FileBarChart },
  { label: "Notifications", to: "/admin/notifications", icon: Bell },
  { label: "Settings", to: "/admin/settings", icon: Settings },
];
